package model;
// Generated Nov 15, 2023 10:46:13 PM by Hibernate Tools 4.3.1



/**
 * Usertable generated by hbm2java
 */
public class Usertable  implements java.io.Serializable {


     private int uid;
     private String fullname;
     private String email;
     private String address;

    public Usertable() {
    }

	
    public Usertable(int uid) {
        this.uid = uid;
    }
    public Usertable(int uid, String fullname, String email, String address) {
       this.uid = uid;
       this.fullname = fullname;
       this.email = email;
       this.address = address;
    }
   
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


