package model;
// Generated Nov 11, 2023 10:16:03 AM by Hibernate Tools 4.3.1



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String image;

    public Products() {
    }

	
    public Products(String name) {
        this.name = name;
    }
    public Products(String name, String description, String image) {
       this.name = name;
       this.description = description;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


